/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sis.ui;

import com.sis.bean.StudBean;
import com.sis.dao.StudDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gagan
 */
public class AddStud extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    public AddStud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 188, 139));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(20, 130, 110, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Enrollment ");
        add(jLabel2);
        jLabel2.setBounds(400, 150, 140, 30);

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                abchandler(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(320, 550, 140, 50);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(100, 140, 270, 40);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(540, 150, 260, 40);

        jButton2.setBackground(new java.awt.Color(255, 153, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
                abchandler(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(500, 550, 150, 50);

        jButton3.setBackground(new java.awt.Color(255, 153, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
                abchandler(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(680, 550, 140, 50);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("College");
        add(jLabel3);
        jLabel3.setBounds(110, 230, 90, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LNCT", ".LNCTS", "LNCTE", "LNCTU" }));
        add(jComboBox1);
        jComboBox1.setBounds(280, 220, 140, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("SEMESTER");
        add(jLabel4);
        jLabel4.setBounds(110, 300, 130, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText(" Branch");
        add(jLabel5);
        jLabel5.setBounds(660, 220, 100, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Gender");
        add(jLabel6);
        jLabel6.setBounds(670, 280, 110, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Subject 1");
        add(jLabel7);
        jLabel7.setBounds(110, 390, 105, 32);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Subject 2");
        add(jLabel8);
        jLabel8.setBounds(110, 450, 130, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Subject 3");
        add(jLabel9);
        jLabel9.setBounds(670, 360, 130, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Subject 4");
        add(jLabel10);
        jLabel10.setBounds(670, 430, 105, 32);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        add(jComboBox2);
        jComboBox2.setBounds(280, 300, 120, 40);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jTextField3);
        jTextField3.setBounds(830, 210, 270, 40);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add(jComboBox3);
        jComboBox3.setBounds(830, 280, 120, 40);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jTextField4);
        jTextField4.setBounds(280, 380, 140, 40);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jTextField5);
        jTextField5.setBounds(280, 450, 140, 40);

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jTextField6);
        jTextField6.setBounds(830, 360, 150, 40);

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jTextField7);
        jTextField7.setBounds(830, 430, 150, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Add New Student");
        add(jLabel11);
        jLabel11.setBounds(470, 40, 330, 50);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Address");
        add(jLabel12);
        jLabel12.setBounds(830, 150, 100, 40);

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8);
        jTextField8.setBounds(950, 150, 250, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText();
        String Enrollment = jTextField2.getText();
        String College = jComboBox1.getSelectedItem().toString();
        String branch = jTextField3.getText();
        int semester = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        String gender = jComboBox3.getSelectedItem().toString();
        String address = jTextField8.getText();
        int sub1 = Integer.parseInt(jTextField4.getText());
        int sub2 = Integer.parseInt(jTextField5.getText());
        int sub3 = Integer.parseInt(jTextField6.getText());
        int sub4 = Integer.parseInt(jTextField7.getText());
        StudBean sb = new StudBean();
        sb.setName(name);
        sb.setAddress(address);
        sb.setEnrollment(Enrollment);
        sb.setBranch(branch);
        sb.setCollege(College);
        sb.setSemester(semester);
        sb.setGender(gender);
        sb.setSub1(sub1);
        sb.setSub2(sub2);
        sb.setSub3(sub3);
        sb.setSub4(sub4);
        StudDAO sd = new StudDAO();
        int x = sd.addStudent(sb);
        if(x>0){
            JOptionPane.showMessageDialog(this, "Student Added Success");
        }
        else{
            JOptionPane.showMessageDialog(this, "Student Not Added");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = jTextField1.getText();
        
        String Enrollment = jTextField2.getText();
        String College = jComboBox1.getSelectedItem().toString();
        String branch = jTextField3.getText();
        int semester = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        String gender = jComboBox3.getSelectedItem().toString();
        String address = jTextField8.getText();
        int sub1 = Integer.parseInt(jTextField4.getText().toString());
        int sub2 = Integer.parseInt(jTextField5.getText().toString());
        int sub3 = Integer.parseInt(jTextField6.getText().toString());
        int sub4 = Integer.parseInt(jTextField7.getText().toString());
        StudBean sb = new StudBean();
        sb.setName(name);
        sb.setAddress(address);
        sb.setEnrollment(Enrollment);
        sb.setBranch(branch);
        sb.setCollege(College);
        sb.setSemester(semester);
        sb.setGender(gender);
        sb.setSub1(sub1);
        sb.setSub2(sub2);
        sb.setSub3(sub3);
        sb.setSub4(sub4);
        StudDAO sd = new StudDAO();
        int x = sd.updateStudent(sb);
        if(x>0){
        JOptionPane.showMessageDialog(this, "Student Update success");
        }
        else{
        JOptionPane.showMessageDialog(this, "Student Not Updated");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String enrollment=jTextField2.getText();
        StudDAO sd=new StudDAO();
        int x=sd.deleteStudent(enrollment);
        if(x>0){
        JOptionPane.showMessageDialog(this, "Student deleted Success");
        }
        else{
        JOptionPane.showMessageDialog(this, "Student Not deleted");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void abchandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abchandler
//        String opn=evt.getActionCommand();
//        StudDAO sd=new StudDAO();
//        StudBean sb=new StudBean();
//        if(opn.equals("Delete")){
//            String empno=jTextField5.getText();
//            int a=sd.deleteStudent(empno);
//            if(a>0){
//            JOptionPane.showMessageDialog(this,"Student Deleted");
//            }
//            else{
//            JOptionPane.showMessageDialog(this,"Student Not Deleted");
//            }
//        }
//        else{
//            String name = jTextField1.getText();
//            String Enrollment = jTextField2.getText();
//            String College = jComboBox1.getSelectedItem().toString();
//            String branch = jTextField3.getText();
//            int semester = Integer.parseInt(jComboBox2.getSelectedItem().toString());
//            String gender = jComboBox3.getSelectedItem().toString();
//            int sub1 = Integer.parseInt(jTextField4.getText().toString());
//            int sub2 = Integer.parseInt(jTextField5.getText().toString());
//            int sub3 = Integer.parseInt(jTextField6.getText().toString());
//            int sub4 = Integer.parseInt(jTextField7.getText().toString());
//            sb.setName(name);
//            sb.setEnrollment(Enrollment);
//            sb.setBranch(branch);
//            sb.setCollege(College);
//            sb.setSemester(semester);
//            sb.setGender(gender);
//            sb.setSub1(sub1);
//            sb.setSub2(sub2);
//            sb.setSub3(sub3);
//            sb.setSub4(sub4);
//
//            if(opn.equals("Save")){
//                int x = sd.addStudent(sb);
//                if(x>0){
//                    JOptionPane.showMessageDialog(this,"Student Added Success");
//                }
//                else{
//                JOptionPane.showMessageDialog(this,"Student Not Added");
//                }
//            }else if(opn.equals("Update")){
//                int y=sd.updateStudent(sb);
//                if(y>0){
//                    JOptionPane.showMessageDialog(this,"Student Updated Success");
//                }
//                else{
//                    JOptionPane.showMessageDialog(this,"Student Not Updated");
//                }
//            }
//        }
    }//GEN-LAST:event_abchandler

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed
    
    public static void main(String[] args) {
        JFrame jf = new JFrame("Student Form");
        jf.setContentPane(new AddStud());
        jf.setBounds(100, 200, 700, 800);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
