/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sis.ui;

import com.sis.dao.UsersDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gagan
 */
public class changePassword extends javax.swing.JPanel {

    /**
     * Creates new form changePassword
     */
    public changePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 188, 139));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Email");
        add(jLabel1);
        jLabel1.setBounds(180, 130, 100, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Old Password");
        add(jLabel2);
        jLabel2.setBounds(180, 200, 250, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("New Password");
        add(jLabel3);
        jLabel3.setBounds(180, 270, 260, 40);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(470, 130, 330, 50);

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(jPasswordField1);
        jPasswordField1.setBounds(470, 200, 330, 50);

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(jPasswordField2);
        jPasswordField2.setBounds(470, 270, 330, 50);

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(370, 400, 240, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email=jTextField1.getText();
        String oldpassword=jPasswordField1.getText();
        String newPassword=jPasswordField2.getText();
        UsersDAO ud=new UsersDAO();
        int x=ud.changePassword(email, oldpassword, newPassword);
        if(x==0)
            JOptionPane.showMessageDialog(this, "Password change Successfully");
        else
            JOptionPane.showMessageDialog(this, "password not change");
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String[] args) {
        JFrame jf = new JFrame("changePassword");
        jf.setContentPane(new changePassword());
        jf.setBounds(100, 200, 700, 800);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
