/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sis.ui;

/**
 *
 * @author gagan
 */
import com.sis.bean.StudBean;
import com.sis.dao.StudDAO;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import javax.swing.JFrame;
public class FindByEnrollmentNo extends javax.swing.JPanel {

    /**
     * Creates new form FindByEnrollmentNo
     */
    public FindByEnrollmentNo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dm = new DefaultListModel();
        jList1 = new javax.swing.JList<>(dm);
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 188, 139));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Find Student By Enrollment Number");
        add(jLabel1);
        jLabel1.setBounds(280, 50, 650, 48);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(420, 150, 320, 40);

        jList1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(260, 340, 640, 190);

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(510, 240, 150, 39);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Enrollment");
        add(jLabel2);
        jLabel2.setBounds(270, 140, 150, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dm.clear();
        String branch = jTextField1.getText();
        StudDAO sd = new StudDAO();
        StudBean sb = sd.findByEnrollmentNo(branch);
            dm.addElement(" "+sb.getName()+" "+sb.getAddress()+" "+sb.getBranch()+" "+sb.getSemester()+" "+" "+sb.getCollege()+" "+sb.getGender()+" "+sb.getGrade()+" "+sb.getStatus());
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String[] args) {
        JFrame jf = new JFrame("FindByEnrollment");
        jf.setContentPane(new FindByEnrollmentNo());
        jf.setBounds(100, 200, 700, 800);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);
    }
    DefaultListModel dm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
