/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sis.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JWindow;

/**
 *
 * @author gagan
 */
public class SplashPanel extends javax.swing.JPanel {

    /**
     * Creates new form SplashPanel
     */
    public SplashPanel() {
        initComponents();
    }
    public void abc(int i){
        jProgressBar1.setValue(i);
    }

    public static void main(String[] args) {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width-428)/2;
        int y = (screen.height-243)/2;
        JWindow jw = new JWindow();
        SplashPanel s = new SplashPanel();
        jw.setContentPane(s);
        jw.setBounds(x,y,428,243);
        jw.setVisible(true);
        for(int i = 1;i<100;i++){
            try {
                Thread.sleep(50);
            } catch (Exception e) {
                e.printStackTrace();
            }
            s.abc(i);
        }
        jw.setVisible(false);
        JFrame jf = new JFrame("Login Form");
        jf.setContentPane(new Login());
        jf.setBounds(x, y, screen.width, screen.height);
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\gagan\\Downloads\\pngegg.png")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 320));

        setLayout(new java.awt.BorderLayout());

        jProgressBar1.setBackground(java.awt.Color.lightGray);
        jProgressBar1.setForeground(java.awt.Color.black);
        jProgressBar1.setToolTipText("");
        add(jProgressBar1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\gagan\\Downloads\\splash.png")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(620, 300));
        jLabel2.setMinimumSize(new java.awt.Dimension(620, 300));
        jLabel2.setName(""); // NOI18N
        add(jLabel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
